#pragma once

#include <process.h>

namespace Client
{
	const unsigned int			g_iWinSizeX = { 1280 };
	const unsigned int			g_iWinSizeY = { 720 };

	enum LEVELID { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_COLOSSEUM, LEVEL_PALACE, LEVEL_CHAOS, LEVEL_NERO, LEVEL_MAZE, LEVEL_SM, LEVEL_END };
	enum OBJSTATE { OBJSTATE_IDLE, OBJSTATE_RUN, OBJSTATE_DEAD };
	enum ANITYPE {ANI_STOP, ANI_LOOP, ANI_BACKTOIDLE, ANI_BACKTOTPSIDLE, ANI_END};
	enum WAY { WAY_FRONT, WAY_FRONTR, WAY_R, WAY_BACKR, WAY_BACK, WAY_BACKL, WAY_L, WAY_FRONTL, WAY_END };
	enum SOUND_CHANNEL {CHANNEL_BGM, CHANNEL_PLAYERVOICE,  CHANNEL_PLAYERFX, CHANNEL_CHARGE ,CHANNEL_WEAPON = 7};

}


extern HWND g_hWnd;

using namespace Client;
using namespace std;
